/* =====================================================================
   pros.idf.immo — dictionnaire commun à toutes les pages
   En-tête, navigation, bandeau final, pied de page.
   Triplets : [français, português, english]
   ===================================================================== */
window.DICO_COMMUN = [
  ["Aller au contenu",
   "Ir para o conteúdo",
   "Skip to content"],
  ["Navigation principale",
   "Navegação principal",
   "Main navigation"],
  ["Comment ça marche",
   "Como funciona",
   "How it works"],
  ["La prime",
   "O prémio",
   "The bonus"],
  ["Vos questions",
   "Perguntas",
   "Your questions"],
  ["Contact",
   "Contacto",
   "Contact"],
  ["Partager une opportunité",
   "Partilhar uma oportunidade",
   "Share an opportunity"],
  ["Vous avez quelqu'un en tête ?",
   "Tem alguém em mente?",
   "Do you have someone in mind?"],
  ["Il vous faut une adresse et une minute. Si vous n'êtes sûr de rien, partagez quand même : c'est nous que ça regarde ensuite.",
   "Basta uma morada e um minuto. Se não tem a certeza de nada, partilhe à mesma: a partir daí o assunto é connosco.",
   "All it takes is an address and a minute. If you are not sure of anything, share it anyway — from there it is our concern, not yours."],
  ["Le réseau des commerçants, artisans et professionnels de proximité",
   "A rede de comerciantes, artesãos e profissionais de proximidade da Île-de-France. Uma informação partilhada, um projeto imobiliário que avança, 1 000 € para si.",
   "The network of local shopkeepers, tradespeople and service providers across the Île-de-France region. One piece of information shared, a property plan moving forward, €1,000 for you."],
  ["Le réseau",
   "A rede",
   "The network"],
  ["La prime de 1 000 €",
   "O prémio de 1 000 €",
   "The €1,000 bonus"],
  ["Notre engagement",
   "O nosso compromisso",
   "Our commitment"],
  ["Mon espace",
   "A minha área",
   "My space"],
  ["Envoyer un SMS",
   "Enviar um SMS",
   "Send a text message"],
  ["Conditions de la prime",
   "Condições do prémio",
   "Bonus terms and conditions"],
  ["Mentions légales",
   "Menções legais",
   "Legal notice"],
  ["Marie-Céline Etave — conseillère en immobilier, Île-de-France.",
   "Marie-Céline Etave — consultora imobiliária, Île-de-France.",
   "Marie-Céline Etave — property adviser, Île-de-France."],
  ["Un site de la famille idf.immo",
   "Um site da família idf.immo",
   "A site from the idf.immo family"]
];
