/* =====================================================================
   pros.idf.immo — dictionnaire de contact.html
   Triplets : [français, português, english]
   ===================================================================== */
window.DICO = [
  ["Me contacter — pros.idf.immo",
   "Contactar-me — pros.idf.immo",
   "Contact me — pros.idf.immo"],
  ["Parlons-en",
   "Vamos falar",
   "Let's talk"],
  ["Une question, un doute, une information à transmettre ? Vous pouvez me joindre directement, quand vous voulez.",
   "Uma pergunta, uma dúvida, uma informação a transmitir? Pode falar comigo diretamente, quando quiser.",
   "A question, a doubt, something to pass on? You can reach me directly, whenever you like."],
  ["Votre interlocutrice",
   "A sua interlocutora",
   "The person you deal with"],
  ["Conseillère en immobilier en Île-de-France. C'est moi qui reçois chaque opportunité, qui appelle les propriétaires et qui vous tiens au courant. Vous n'aurez jamais affaire à un standard ni à un formulaire anonyme.",
   "Consultora imobiliária na Île-de-France. Sou eu que recebo cada oportunidade, que telefono aos proprietários e que a mantenho a par. Nunca lidará com uma central telefónica nem com um formulário anónimo.",
   "Property adviser in the Île-de-France region. I am the one who receives every opportunity, calls the owners and keeps you informed. You will never deal with a switchboard or an anonymous form."],
  ["💬 Envoyer un SMS",
   "💬 Enviar um SMS",
   "💬 Send a text message"],
  ["Quand m'appeler ?",
   "Quando me telefonar?",
   "When to call me"],
  ["Aussi souvent que vous le souhaitez. Il n'y a pas de mauvaise question, et vous ne me dérangez pas : c'est mon métier.",
   "As vezes que quiser. Não há perguntas parvas, e não me está a incomodar: é o meu trabalho.",
   "As often as you like. There is no such thing as a bad question, and you are not disturbing me: this is my job."],
  ["Avant de partager",
   "Antes de partilhar",
   "Before you share"],
  [", si vous vous demandez si votre situation entre dans le cadre, ou si vous ne savez pas comment en parler à votre client.",
   ", se tem dúvidas se a sua situação se enquadra, ou se não sabe como falar disso com o seu cliente.",
   ", if you are wondering whether your situation fits, or how to raise it with your customer."],
  ["Au lieu du formulaire",
   "Em vez do formulário",
   "Instead of the form"],
  [", si vous préférez me raconter les choses de vive voix. Un appel ou un SMS valent un envoi : j'enregistre l'opportunité avec vous, et la date de votre appel fait foi de la même façon.",
   ", se prefere contar-me as coisas de viva voz. Um telefonema ou um SMS valem tanto como um envio: registo a oportunidade consigo, e a data do seu telefonema conta da mesma maneira.",
   ", if you would rather tell me in person. A call or a text is worth as much as a submission: I record the opportunity with you, and the date of your call counts in exactly the same way."],
  ["Après avoir partagé",
   "Depois de ter partilhado",
   "After you have shared"],
  [", pour savoir où en est votre opportunité, ou pour ajouter un détail dont vous vous souvenez plus tard.",
   ", para saber em que ponto está a sua oportunidade, ou para acrescentar um pormenor de que se lembrou mais tarde.",
   ", to find out where your opportunity stands, or to add a detail you remember later on."],
  ["Sur la prime",
   "Sobre o prémio",
   "About the bonus"],
  [", la facture, les impôts, la convention : si quelque chose n'est pas clair sur le site, dites-le-moi. C'est le site qu'il faudra corriger, pas vous.",
   ", a fatura, os impostos, o contrato: se alguma coisa não estiver clara no site, diga-me. É o site que terá de ser corrigido, não você.",
   ", the invoice, tax, the agreement: if anything on this site is unclear, tell me. It is the site that needs fixing, not you."],
  ["Vous pouvez aussi donner mon numéro",
   "Também pode dar o meu número",
   "You can also give out my number"],
  ["Rien ne vous oblige à faire l'intermédiaire jusqu'au bout. Si un client préfère m'appeler lui-même,",
   "Nada o obriga a servir de intermediário até ao fim. Se um cliente preferir telefonar-me ele próprio,",
   "Nothing obliges you to act as go-between all the way. If a customer would rather call me themselves,"],
  ["donnez-lui le 06 60 98 92 92",
   "dê-lhe o 06 60 98 92 92",
   "give them 06 60 98 92 92"],
  [": beaucoup de gens font la démarche plus volontiers quand elle vient d'eux.",
   ": muita gente dá o passo com mais vontade quando parte de si própria.",
   ": many people take the step far more readily when it comes from them."],
  ["Vous ne perdez rien à le faire. Du moment que vous avez partagé l'opportunité avec ses coordonnées, le rapprochement se fait automatiquement quand il appelle, et",
   "Não perde nada com isso. Desde que tenha partilhado a oportunidade com os contactos dele, a associação faz-se automaticamente quando ele telefona, e",
   "You lose nothing by doing so. As long as you have shared the opportunity with their contact details, the match is made automatically when they call, and"],
  ["la prime vous revient",
   "o prémio é seu",
   "the bonus is yours"],
  [". Pensez juste à cocher la case prévue dans le formulaire, pour que je sache d'où vient l'appel.",
   ". Basta assinalar a opção prevista no formulário, para eu saber de onde vem o telefonema.",
   ". Just remember to tick the box provided on the form, so I know where the call is coming from."],
  ["Le plus simple, souvent",
   "Muitas vezes, o mais simples",
   "Often the simplest way"],
  ["Un SMS. « Bonjour, je suis coiffeuse rue du Général-de-Gaulle à Enghien-les-Bains, une cliente m'a parlé de vendre, j'ai peut-être quelque chose pour vous. » Je vous rappelle, et on regarde ensemble.",
   "Um SMS. «Bom dia, sou cabeleireira na rue du Général-de-Gaulle em Enghien-les-Bains, uma cliente falou-me em vender, talvez tenha alguma coisa para si.» Eu ligo de volta e vemos isso juntos.",
   "A text message. “Hello, I run the hair salon on rue du Général-de-Gaulle in Enghien-les-Bains, a customer mentioned selling, I may have something for you.” I call you back and we look at it together."],
  ["Ce que je fais de ce que vous me dites",
   "O que faço com o que me diz",
   "What I do with what you tell me"],
  ["Je qualifie l'information, je prends contact avec le propriétaire dans le respect de ce que vous avez choisi, et je vous tiens au courant à chaque étape. Rien n'est transmis à des tiers, rien n'est revendu.",
   "Avalio a informação, contacto o proprietário respeitando o que escolheu, e mantenho-o a par em cada etapa. Nada é transmitido a terceiros, nada é vendido.",
   "I assess the information, I contact the owner in line with what you chose, and I keep you informed at every step. Nothing is passed to third parties, nothing is sold on."],
  ["Et si vous préférez que votre nom ne soit jamais prononcé auprès du propriétaire, dites-le-moi : c'est vous qui décidez, à chaque fois.",
   "E se prefere que o seu nome nunca seja dito ao proprietário, diga-me: é você que decide, de cada vez.",
   "And if you would rather your name were never mentioned to the owner, tell me: you decide, every time."],
  ["Voir nos engagements →",
   "Ver os nossos compromissos →",
   "See our commitments →"],
  ["Vous préférez le formulaire ?",
   "Prefere o formulário?",
   "Would you rather use the form?"],
  ["Il tient en trois écrans et prend moins d'une minute. Vous recevez aussitôt un e-mail de confirmation avec votre numéro d'opportunité.",
   "Tem três ecrãs e demora menos de um minuto. Recebe logo um e-mail de confirmação com o seu número de oportunidade.",
   "It runs to three screens and takes under a minute. You immediately receive a confirmation email with your opportunity number."],
  ["Comment ça marche ?",
   "Como funciona?",
   "How it works"],
  ["Le réseau des commerçants, artisans et professionnels de proximité d'Île-de-France. Une information partagée, un projet immobilier qui avance, 1 000 € pour vous.",
   "A rede de comerciantes, artesãos e profissionais de proximidade da Île-de-France. Uma informação partilhada, um projeto imobiliário que avança, 1 000 € para si.",
   "The network of local shopkeepers, tradespeople and service providers across the Île-de-France region. One piece of information shared, a property plan moving forward, €1,000 for you."]
];
